defmodule Spectre.Prism.ReqLLMAdaptersTest.Client do
  @moduledoc false

  def generate_text(model, prompt, opts) do
    send(Keyword.fetch!(opts, :test_pid), {:req_llm_generate, model, prompt, opts})

    case Keyword.get(opts, :fake_error) do
      nil ->
        {:ok,
         %{
           id: "req_1",
           model: model.id,
           text: "generated by #{model.provider}",
           usage: %{input_tokens: 4, output_tokens: 3, total_tokens: 7},
           finish_reason: :stop
         }}

      error ->
        {:error, error}
    end
  end

  def embed(model, input, opts) do
    send(Keyword.fetch!(opts, :test_pid), {:req_llm_embed, model, input, opts})
    {:ok, [1, 2, 3]}
  end
end

defmodule Spectre.Prism.ReqLLMAdaptersTest.Serving do
  @moduledoc false

  def batched_run({pid, :generation}, input) do
    send(pid, {:bumblebee_generation, input})

    %{
      results: [
        %{text: "local result", token_summary: %{input: 5, output: 2, padding: 0}}
      ]
    }
  end

  def batched_run({pid, :embedding}, input) do
    send(pid, {:bumblebee_embedding, input})
    %{embedding: [0.25, 0.5, 0.75]}
  end
end

defmodule Spectre.Prism.ReqLLMAdaptersTest.CustomAdapter do
  @moduledoc false

  use Spectre.Prism.Adapter.ReqLLM,
    provider: :venice,
    api_key_env: "VENICE_API_KEY",
    profiles: [
      fast: [model: "venice-fast", rank: 10],
      balanced: [model: "venice-balanced", rank: 20],
      deep: [model: "venice-deep", rank: 30]
    ]
end

defmodule Spectre.Prism.ReqLLMAdaptersTest do
  use ExUnit.Case, async: true

  alias Spectre.Inference.Response
  alias Spectre.Prism.Adapter.Error
  alias Spectre.Prism.Adapters
  alias Spectre.Prism.Adapters.Anthropic
  alias Spectre.Prism.Adapters.Bumblebee
  alias Spectre.Prism.Adapters.Cerebras
  alias Spectre.Prism.Adapters.DeepSeek
  alias Spectre.Prism.Adapters.Groq
  alias Spectre.Prism.Adapters.Mistral
  alias Spectre.Prism.Adapters.XAI
  alias Spectre.Prism.Registry
  alias Spectre.Prism.ReqLLMAdaptersTest.Client
  alias Spectre.Prism.ReqLLMAdaptersTest.CustomAdapter
  alias Spectre.Prism.ReqLLMAdaptersTest.Serving
  alias Spectre.Prompt.Plan

  @req_llm_adapters [Anthropic, DeepSeek, Groq, XAI, Mistral, Cerebras]

  test "bundled identifiers and aliases resolve without adapter boilerplate" do
    assert Adapters.ids() == [
             :openai,
             :openrouter,
             :ollama,
             :gemini,
             :anthropic,
             :deepseek,
             :groq,
             :xai,
             :mistral,
             :cerebras,
             :bumblebee
           ]

    assert {:ok, Anthropic} = Adapters.fetch(:anthropic)
    assert {:ok, Anthropic} = Adapters.fetch(:claude)
    assert {:ok, Spectre.Prism.Adapters.Gemini} = Adapters.fetch(:google)
    assert {:ok, XAI} = Adapters.fetch(:grok)
    assert {:error, {:unknown_prism_builtin_provider, :unknown}} = Adapters.fetch(:unknown)
    assert_raise ArgumentError, fn -> Adapters.fetch!(:unknown) end
  end

  test "the Stack DSL supports one-line bundled providers and option-only declarations" do
    shorthand =
      quote do
        provider(:claude)
      end

    assert {:ok, config} = Spectre.Prism.compile([], shorthand, __ENV__)
    assert config.providers == [claude: Anthropic]

    configured =
      quote do
        provider(:deepseek, models: [fast: "my-fast-model"], embedding: false)
      end

    assert {:ok, config} = Spectre.Prism.compile([], configured, __ENV__)

    assert config.providers == [
             deepseek: {DeepSeek, [models: [fast: "my-fast-model"], embedding: false]}
           ]

    unknown =
      quote do
        provider(:not_a_provider)
      end

    assert {:error, {:unknown_prism_builtin_provider, :not_a_provider}} =
             Spectre.Prism.compile([], unknown, __ENV__)
  end

  test "ReqLLM-backed adapters expose three executable Spectre profiles" do
    for adapter <- @req_llm_adapters do
      assert {:ok, registry} = Registry.build([{:provider, adapter}])
      assert Enum.map(Registry.profiles(registry), &elem(&1, 0)) == [:fast, :balanced, :deep]

      for {_level, opts} <- Registry.profiles(registry) do
        assert {^adapter, :complete_plan, adapter_opts} = Keyword.fetch!(opts, :model)
        assert adapter_opts[:req_llm_provider]
        assert is_binary(adapter_opts[:model])
      end
    end

    assert {:ok, custom} = Registry.build([{:venice, CustomAdapter}])
    assert Enum.map(Registry.profiles(custom), &elem(&1, 0)) == [:fast, :balanced, :deep]
  end

  test "Anthropic maps ReqLLM responses and prompt plans to Spectre responses" do
    opts = [
      model: "claude-sonnet-4-6",
      req_llm_module: Client,
      test_pid: self(),
      api_key: "runtime-only",
      max_output_tokens: 64
    ]

    assert {:ok,
            %Response{
              text: "generated by anthropic",
              provider_request_id: "req_1",
              usage: %{total_tokens: 7}
            } = response} = Anthropic.complete("hello", opts)

    assert response.metadata.model == "claude-sonnet-4-6"
    assert response.metadata.finish_reason == :stop

    assert_receive {:req_llm_generate, %{provider: :anthropic, id: "claude-sonnet-4-6"}, "hello",
                    req_opts}

    assert req_opts[:api_key] == "runtime-only"
    assert req_opts[:max_tokens] == 64
    refute Keyword.has_key?(req_opts, :max_output_tokens)

    plan = %Plan{
      instructions: [%{content: "system rules"}],
      context: [],
      task: [%{content: "answer"}]
    }

    assert {:ok, %Response{text: "generated by anthropic"}} =
             Anthropic.complete_plan(plan, opts)

    assert_receive {:req_llm_generate, _model, "answer", plan_opts}
    assert plan_opts[:system_prompt] == "system rules"
  end

  test "ReqLLM failures are sanitized and preserve retry-relevant HTTP status" do
    upstream =
      ReqLLM.Error.API.Request.exception(
        reason: "body contains private prompt",
        status: 429,
        provider_code: "rate_limit_exceeded",
        response_body: %{"secret" => "value"}
      )

    assert {:error,
            %Error{
              provider: :anthropic,
              kind: :http,
              status: 429,
              code: "rate_limit_exceeded",
              retryable?: true
            } = error} =
             Anthropic.complete("private prompt",
               model: "claude-haiku-4-5",
               req_llm_module: Client,
               test_pid: self(),
               fake_error: upstream
             )

    refute inspect(error) =~ "private prompt"
    refute inspect(error) =~ "secret"
  end

  test "Mistral delegates embeddings and publishes dimensions" do
    assert {:ok, [1.0, 2.0, 3.0]} =
             Mistral.embed("embed me",
               model: "mistral-embed",
               req_llm_module: Client,
               test_pid: self()
             )

    assert_receive {:req_llm_embed, %{provider: :mistral, id: "mistral-embed"}, "embed me", _opts}

    assert {:ok, 1024} = Mistral.load("mistral-embed")
  end

  test "Bumblebee maps local generation and optional embedding servings" do
    assert {:ok,
            %Response{
              text: "local result",
              usage: %{input_tokens: 5, output_tokens: 2, total_tokens: 7}
            }} =
             Bumblebee.complete("local prompt",
               model: "local-medium",
               serving: {self(), :generation},
               serving_module: Serving
             )

    assert_receive {:bumblebee_generation, "local prompt"}

    assert {:ok, [0.25, 0.5, 0.75]} =
             Bumblebee.embed("vector me",
               model: "local-embedding",
               embedding_serving: {self(), :embedding},
               serving_module: Serving
             )

    assert_receive {:bumblebee_embedding, "vector me"}

    assert {:error, %Error{kind: :configuration, code: :missing_serving}} =
             Bumblebee.complete("prompt", model: "local-small")
  end
end
