defmodule Spectre.Prism.ReqLLMAdaptersTest.Client do
  @moduledoc false

  def generate_text(model, prompt, opts) do
    send(Keyword.fetch!(opts, :test_pid), {:req_llm_generate, model, prompt, opts})

    case Keyword.get(opts, :fake_error) do
      nil ->
        {:ok,
         %{
           id: "req_1",
           model: model.id,
           text: "generated by #{model.provider}",
           usage: %{input_tokens: 4, output_tokens: 3, total_tokens: 7},
           finish_reason: :stop
         }}

      error ->
        {:error, error}
    end
  end

  def embed(model, input, opts) do
    send(Keyword.fetch!(opts, :test_pid), {:req_llm_embed, model, input, opts})
    {:ok, [1, 2, 3]}
  end
end

defmodule Spectre.Prism.ReqLLMAdaptersTest.Serving do
  @moduledoc false

  def batched_run({pid, :generation}, input) do
    send(pid, {:bumblebee_generation, input})

    %{
      results: [
        %{text: "local result", token_summary: %{input: 5, output: 2, padding: 0}}
      ]
    }
  end

  def batched_run({pid, :embedding}, input) do
    send(pid, {:bumblebee_embedding, input})
    %{embedding: [0.25, 0.5, 0.75]}
  end

  def batched_run({pid, {:return, output}}, input) do
    send(pid, {:bumblebee_return, input})
    output
  end

  def batched_run({_pid, :raise}, _input), do: raise("private serving error")
  def batched_run({_pid, :exit}, _input), do: exit(:private_serving_exit)
  def batched_run({_pid, :throw}, _input), do: throw(:private_serving_throw)

  def run({pid, output}, input) do
    send(pid, {:bumblebee_run, input})
    output
  end
end

defmodule Spectre.Prism.ReqLLMAdaptersTest.CustomAdapter do
  @moduledoc false

  use Spectre.Prism.Adapter.ReqLLM,
    provider: :venice,
    api_key_env: "VENICE_API_KEY",
    profiles: [
      fast: [model: "venice-fast", rank: 10],
      balanced: [model: "venice-balanced", rank: 20],
      deep: [model: "venice-deep", rank: 30]
    ]
end

defmodule Spectre.Prism.ReqLLMAdaptersTest do
  use ExUnit.Case, async: true

  alias Spectre.Inference.Response
  alias Spectre.Prism.Adapter.Error
  alias Spectre.Prism.Adapters
  alias Spectre.Prism.Adapters.Anthropic
  alias Spectre.Prism.Adapters.Bumblebee
  alias Spectre.Prism.Adapters.Cerebras
  alias Spectre.Prism.Adapters.DeepSeek
  alias Spectre.Prism.Adapters.Gemini
  alias Spectre.Prism.Adapters.Groq
  alias Spectre.Prism.Adapters.Mistral
  alias Spectre.Prism.Adapters.Ollama
  alias Spectre.Prism.Adapters.OpenAI
  alias Spectre.Prism.Adapters.OpenRouter
  alias Spectre.Prism.Adapters.XAI
  alias Spectre.Prism.Registry
  alias Spectre.Prism.ReqLLMAdaptersTest.Client
  alias Spectre.Prism.ReqLLMAdaptersTest.CustomAdapter
  alias Spectre.Prism.ReqLLMAdaptersTest.Serving
  alias Spectre.Prompt.Plan

  @req_llm_adapters [
    OpenAI,
    Gemini,
    OpenRouter,
    Ollama,
    Anthropic,
    DeepSeek,
    Groq,
    XAI,
    Mistral,
    Cerebras
  ]

  test "bundled identifiers and aliases resolve without adapter boilerplate" do
    assert Adapters.ids() == [
             :openai,
             :openrouter,
             :ollama,
             :gemini,
             :anthropic,
             :deepseek,
             :groq,
             :xai,
             :mistral,
             :cerebras,
             :bumblebee
           ]

    assert {:ok, Anthropic} = Adapters.fetch(:anthropic)
    assert {:ok, Anthropic} = Adapters.fetch(:claude)
    assert {:ok, Spectre.Prism.Adapters.Gemini} = Adapters.fetch(:google)
    assert {:ok, XAI} = Adapters.fetch(:grok)
    assert {:error, {:unknown_prism_builtin_provider, :unknown}} = Adapters.fetch(:unknown)
    assert_raise ArgumentError, fn -> Adapters.fetch!(:unknown) end
  end

  test "the Stack DSL supports one-line bundled providers and option-only declarations" do
    shorthand =
      quote do
        provider(:claude)
      end

    assert {:ok, config} = Spectre.Prism.compile([], shorthand, __ENV__)
    assert config.providers == [claude: Anthropic]

    configured =
      quote do
        provider(:deepseek, models: [fast: "my-fast-model"], embedding: false)
      end

    assert {:ok, config} = Spectre.Prism.compile([], configured, __ENV__)

    assert config.providers == [
             deepseek: {DeepSeek, [models: [fast: "my-fast-model"], embedding: false]}
           ]

    unknown =
      quote do
        provider(:not_a_provider)
      end

    assert {:error, {:unknown_prism_builtin_provider, :not_a_provider}} =
             Spectre.Prism.compile([], unknown, __ENV__)
  end

  test "ReqLLM-backed adapters expose three executable Spectre profiles" do
    for adapter <- @req_llm_adapters do
      assert {:ok, registry} = Registry.build([{:provider, adapter}])
      assert Enum.map(Registry.profiles(registry), &elem(&1, 0)) == [:fast, :balanced, :deep]

      for {_level, opts} <- Registry.profiles(registry) do
        assert {^adapter, :complete_plan, adapter_opts} = Keyword.fetch!(opts, :model)
        assert adapter_opts[:req_llm_provider]
        assert is_binary(adapter_opts[:model])
      end
    end

    assert {:ok, custom} = Registry.build([{:venice, CustomAdapter}])
    assert Enum.map(Registry.profiles(custom), &elem(&1, 0)) == [:fast, :balanced, :deep]
  end

  test "multiple providers can map catalog levels to unique profile identifiers" do
    assert {:ok, registry} =
             Registry.build([
               {:anthropic, Anthropic,
                levels: [fast: :claude_fast, balanced: :claude_balanced, deep: :claude_deep]},
               {:deepseek, DeepSeek,
                levels: [
                  fast: :deepseek_fast,
                  balanced: :deepseek_balanced,
                  deep: :deepseek_deep
                ]}
             ])

    assert Enum.map(Registry.profiles(registry), &elem(&1, 0)) == [
             :claude_fast,
             :claude_balanced,
             :claude_deep,
             :deepseek_fast,
             :deepseek_balanced,
             :deepseek_deep
           ]

    assert Registry.classifier(registry) == nil
  end

  test "Anthropic maps ReqLLM responses and prompt plans to Spectre responses" do
    opts = [
      model: "claude-sonnet-4-6",
      req_llm_module: Client,
      test_pid: self(),
      api_key: "runtime-only",
      max_output_tokens: 64
    ]

    assert {:ok,
            %Response{
              text: "generated by anthropic",
              provider_request_id: "req_1",
              usage: %{total_tokens: 7}
            } = response} = Anthropic.complete("hello", opts)

    assert response.metadata.model == "claude-sonnet-4-6"
    assert response.metadata.finish_reason == :stop

    assert_receive {:req_llm_generate, %{provider: :anthropic, id: "claude-sonnet-4-6"}, "hello",
                    req_opts}

    assert req_opts[:api_key] == "runtime-only"
    assert req_opts[:max_tokens] == 64
    refute Keyword.has_key?(req_opts, :max_output_tokens)

    plan = %Plan{
      instructions: [%{content: "system rules"}],
      context: [],
      task: [%{content: "answer"}]
    }

    assert {:ok, %Response{text: "generated by anthropic"}} =
             Anthropic.complete_plan(plan, opts)

    assert_receive {:req_llm_generate, _model, "answer", plan_opts}
    assert plan_opts[:system_prompt] == "system rules"
  end

  test "ReqLLM failures are sanitized and preserve retry-relevant HTTP status" do
    upstream =
      ReqLLM.Error.API.Request.exception(
        reason: "body contains private prompt",
        status: 429,
        provider_code: "rate_limit_exceeded",
        response_body: %{"secret" => "value"}
      )

    assert {:error,
            %Error{
              provider: :anthropic,
              kind: :http,
              status: 429,
              code: "rate_limit_exceeded",
              retryable?: true
            } = error} =
             Anthropic.complete("private prompt",
               model: "claude-haiku-4-5",
               req_llm_module: Client,
               test_pid: self(),
               fake_error: upstream
             )

    refute inspect(error) =~ "private prompt"
    refute inspect(error) =~ "secret"
  end

  test "Mistral delegates embeddings and publishes dimensions" do
    assert {:ok, [1.0, 2.0, 3.0]} =
             Mistral.embed("embed me",
               model: "mistral-embed",
               req_llm_module: Client,
               test_pid: self()
             )

    assert_receive {:req_llm_embed, %{provider: :mistral, id: "mistral-embed"}, "embed me", _opts}

    assert {:ok, 1024} = Mistral.load("mistral-embed")
  end

  test "Bumblebee maps local generation and optional embedding servings" do
    assert {:ok,
            %Response{
              text: "local result",
              usage: %{input_tokens: 5, output_tokens: 2, total_tokens: 7}
            }} =
             Bumblebee.complete("local prompt",
               model: "local-medium",
               serving: {self(), :generation},
               serving_module: Serving
             )

    assert_receive {:bumblebee_generation, "local prompt"}

    assert {:ok, [0.25, 0.5, 0.75]} =
             Bumblebee.embed("vector me",
               model: "local-embedding",
               embedding_serving: {self(), :embedding},
               serving_module: Serving
             )

    assert_receive {:bumblebee_embedding, "vector me"}

    assert {:error, %Error{kind: :configuration, code: :missing_serving}} =
             Bumblebee.complete("prompt", model: "local-small")
  end

  test "Bumblebee supports prompt plans, model serving maps, and output variants" do
    plan = %Plan{
      instructions: [%{content: "local policy"}],
      context: [],
      task: [%{content: "answer locally"}]
    }

    string_result = %{
      "results" => [
        %{
          "text" => "mapped local result",
          "token_summary" => %{"input" => 3, "output" => 2}
        }
      ]
    }

    assert {:ok,
            %Response{
              text: "mapped local result",
              usage: %{input_tokens: 3, output_tokens: 2, total_tokens: 5}
            }} =
             Bumblebee.complete_plan(plan,
               model: "local-medium",
               servings: %{"local-medium": {self(), {:return, string_result}}},
               serving_module: Serving
             )

    assert_receive {:bumblebee_return, "local policy\n\nanswer locally"}

    assert {:ok, %Response{text: "plain local result"}} =
             Bumblebee.complete("plain",
               model: "local-small",
               servings: ["local-small": {self(), "plain local result"}],
               serving_module: Serving,
               serving_function: :run
             )

    assert_receive {:bumblebee_run, "plain"}
  end

  test "Bumblebee validates serving configuration and contains serving failures" do
    assert {:error, %Error{code: :invalid_prompt}} = Bumblebee.complete(:invalid)
    assert {:error, %Error{code: :invalid_options}} = Bumblebee.complete("prompt", [:invalid])
    assert {:error, %Error{code: :invalid_prompt_plan}} = Bumblebee.complete_plan(:invalid, [])
    assert {:error, %Error{code: :invalid_model}} = Bumblebee.load("")
    assert {:error, %Error{code: :invalid_embedding_input}} = Bumblebee.embed("")

    assert {:error, %Error{code: :missing_embedding_serving}} =
             Bumblebee.embed("text", model: "local-embedding")

    assert {:error, %Error{code: :nx_serving_unavailable}} =
             Bumblebee.complete("prompt", serving: :serving, serving_module: "invalid")

    assert {:error, %Error{code: :invalid_serving_function}} =
             Bumblebee.complete("prompt",
               serving: :serving,
               serving_module: Serving,
               serving_function: :missing
             )

    for {mode, code} <- [raise: :serving_exception, exit: :serving_exit, throw: :serving_failure] do
      assert {:error, %Error{kind: :transport, code: ^code}} =
               Bumblebee.complete("prompt",
                 serving: {self(), mode},
                 serving_module: Serving
               )
    end
  end

  test "Bumblebee normalizes embedding variants and probes dimensions" do
    for output <- [
          %{"embedding" => [1, 2]},
          %{embedding: [1, 2]},
          [1, 2],
          Nx.tensor([1, 2])
        ] do
      assert {:ok, [1.0, 2.0]} =
               Bumblebee.embed("text",
                 embedding_serving: {self(), {:return, output}},
                 serving_module: Serving
               )
    end

    assert {:ok, 3} =
             Bumblebee.load("local-embedding",
               embedding_serving: {self(), :embedding},
               serving_module: Serving
             )

    assert {:ok, 16} = Bumblebee.download("local-embedding", dimensions: 16)

    for output <- [[], [1, :invalid], %{"unexpected" => true}] do
      assert {:error, %Error{code: :invalid_embedding_vector}} =
               Bumblebee.embed("text",
                 embedding_serving: {self(), {:return, output}},
                 serving_module: Serving
               )
    end
  end

  test "Bumblebee rejects malformed generation output and sanitizes token counts" do
    result = %{
      results: [
        %{text: "safe", token_summary: %{input: -1, output: "private", padding: 9}}
      ]
    }

    assert {:ok, %Response{text: "safe", usage: %{total_tokens: 0}}} =
             Bumblebee.complete("prompt",
               serving: {self(), {:return, result}},
               serving_module: Serving
             )

    assert {:error, %Error{code: :missing_output_text}} =
             Bumblebee.complete("prompt",
               serving: {self(), {:return, %{results: []}}},
               serving_module: Serving
             )
  end
end
